# Usa una imagen base de OpenJDK para Java 17
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el jar compilado de tu aplicación Spring Boot al contenedor
COPY target/api-rest-1.0.0-RELEASE.jar api-rest-1.0.0-RELEASE.jar

# Expone el puerto 8080 en el contenedor
EXPOSE 8080

# Comando para ejecutar la aplicación Spring Boot al iniciar el contenedor
CMD ["java", "-jar", "api-rest-1.0.0-RELEASE.jar"]
